owner: ss14-art
repo: uptime
user-agent: ss14-art

sites:
  - name: SS14 Auth
    url: https://auth.ss14.art
  - name: SS14 RSS & Changelog
    url: https://rss.ss14.art
  - name: SS14 Website
    url: https://ss14.art
  - name: SS14 Wiki
    url: https://wiki.ss14.art
  - name: SpaceStation14 Website
    url: https://spacestation14.com
  - name: SS14 Hub API
    url: https://hub.spacestation14.com/api/servers

  - name: Ratgore Game Server (TCP)
    check: "tcp-ping"
    url: de.veroid.net
    port: 10007
  - name: PostgreSQL (TCP)
    check: "tcp-ping"
    url: de.veroid.net
    port: 10512

  - name: SS14 Auth API
    url: https://auth.spacestation14.com/api/query/userid?userid=$TOP_SECRET_VALID_SS14_USER

status-website:
  name: SS14 Status
  baseUrl: /uptime
  theme: dark
