owner: ss14-art
repo: uptime
user-agent: ss14-art

sites:
  - name: SS14 Auth
    url: https://auth.ss14.art
    icon: https://i.postimg.cc/5tfrWmXR/logo.png

  - name: SS14 RSS & Changelog
    url: https://rss.ss14.art
    icon: https://i.postimg.cc/5tfrWmXR/logo.png

  - name: SS14 Website
    url: https://ss14.art
    icon: https://i.postimg.cc/5tfrWmXR/logo.png

  - name: SS14 Wiki
    url: https://wiki.ss14.art
    icon: https://i.postimg.cc/BvYfhzmk/favicon.png

  - name: SpaceStation14 Website
    url: https://spacestation14.com
    icon: https://spacestation14.com/favicon.ico

  - name: SS14 Hub API
    url: https://hub.spacestation14.com/api/servers
    icon: https://spacestation14.com/favicon.ico
    expectedStatusCodes:
      - 200
      - 404

  - name: Ratgore Game Server (TCP)
    check: tcp-ping
    url: de.veroid.net
    port: 10007
    icon: https://i.postimg.cc/BvYfhzmk/favicon.png

  - name: PostgreSQL (TCP)
    check: tcp-ping
    url: de.veroid.net
    port: 10512
    icon: https://i.postimg.cc/5tfrWmXR/logo.png

  - name: SS14 Auth API
    url: https://auth.spacestation14.com/api/query/userid?userid=$TOP_SECRET_VALID_SS14_USER
    icon: https://spacestation14.com/favicon.ico
    expectedStatusCodes:
      - 200
    __dangerous__body_down_if_text_missing: '"userId"'

status-website:
  name: SS14 Status
  baseUrl: /uptime/
  theme: night
  logoUrl: https://i.postimg.cc/5tfrWmXR/logo.png
  favicon: https://i.postimg.cc/5tfrWmXR/logo.png
  faviconSvg: https://i.postimg.cc/5tfrWmXR/logo.png
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/ss14-art/uptime
